### ISSUE TITLE
Invalid Plug-in File

### ISSUE THREAD

**Issue by step2live** [baldogiRichard/apex-copy-excel-to-ig#1]
Hello,

i tried to install this plugin but it doesn't work: "Invalid Plug-in" File.
![screenshot](https://github.com/baldogiRichard/apex-copy-excel-to-ig/assets/150419237/4a700d32-50d1-42a0-84d8-7f898ab72f47)

Do you tried this plugin in the last days? Or do you have an instruction guideline for me? We use the version 20.1 of APEX.

Thanks a lot, i really need this very nice plugin!
Best regards
Mirko

**Comment by baldogiRichard** [comment]
Hi Mirko!

The plugin was created on APEX 22.2 or later, so what you can do is to create the plugin from scratch and copy the files and attributes from a later version of apex.

Try to install my application on apex.oracle.com and from that copy the plugin as it was mentioned above.

![image](https://github.com/baldogiRichard/apex-copy-excel-to-ig/assets/100072414/f773e618-85df-4a95-9084-b7a946eb5c6d)


Br,

Richard
