### ISSUE TITLE
SAVE IG 

### ISSUE THREAD

**Issue by JANGKOOK63** [baldogiRichard/apex-copy-excel-to-ig#2]
Hello.  Very thanks for your contribution for Excel To IG,

Question.
1. emp data into IG by Copy/Paste successfully. 
2. Click SAVE  button for save into EMP table 
3.  EMP-Save Interactive Grid Data of Process 
    could not get the column values.(EMPNO, ENAME, JOB etc).
   ex)  CASE :APEX$ROW_STATUS WHEN 'C' THEN   INSERT INTO EMP.....VALUES (:EMPNO, :ENAME, :JOB.. etc);
   could not get value of  all of column.
any ideas?

**Comment by baldogiRichard** [comment]
Hi!

Could you please be more specific?

If I understand correctly you are trying to insert the new rows by specifying a process when saving the IG, but only empty records are inserted?

Thank you,

BR,

Richard

**Comment by JANGKOOK63** [comment]
Very Thanks for your response.
i have  5 years APEX Developer and many experience APEX projects.
Your plugins is useful for me and i would like apply it on my project.but,
has some problem.
Please guide me.

Test Procedure as below.

1. I downloaded your sample application and imported it in to my workspace.

2. on your sample application has no SAVE button and Process. so i add a
Button (SAVE) and create a process as below.
and Added  a Process for Insertion .
[image: image.png]


after that.

3. Copy a record from Excel
[image: image.png]
and
Paste it on IG.

[image: image.png]

Paste was good
4. and push [Save] Button.
[image: image.png]

as you seen above clip.  Column on IG could not recognized a value.
so, i changed a attribute of EMPNO, DEPTNO :  [Vaue Requied] to Off. and
Save again.
then
[image: image.png]

Insertion Process cloud not recognized the all of column values on IG's
pasted values.


Copy and Paste From EXCEL to IG grid was  *OK*. but could not insert this
value into EMP Table.

Please check this simple process and Let me know how to insert IG'a values.
SK.



2024년 2월 5일 (월) 오후 7:46, Báldogi Richárd ***@***.***>님이 작성:

**Comment by baldogiRichard** [comment]
I can't see the attached images but I've made a small change which stringifies all number values when inserting to the grid.

![image](https://github.com/baldogiRichard/apex-copy-excel-to-ig/assets/100072414/59d5e533-910b-43a7-8ccf-f1409102d25b)


After that the validation messages just gone.

Could you please test it yourself ? You can use this link below for testing:

https://apex.oracle.com/pls/apex/r/rmzrt/apex-plugins-by-richard-baldogi197763/copy-excel-to-interactive-grid

Richard

**Comment by JANGKOOK63** [comment]
Hi Richard.

I just tested it as your link and Insert was OK..
any plugins update?

Please let me know.

Very Thanks
sk.




2024년 2월 8일 (목) 오후 8:01, Báldogi Richárd ***@***.***>님이 작성:

**Comment by baldogiRichard** [comment]
I will update the plugin soon. If you need it asap, please update the plugin Javascript file (Shared Components -> Plugins -> The plugin -> Files -> js/script.js) in your workspace.

from

![image](https://github.com/baldogiRichard/apex-copy-excel-to-ig/assets/100072414/185adc38-7153-4c05-9afb-066fa74e5afe)


to

![image](https://github.com/baldogiRichard/apex-copy-excel-to-ig/assets/100072414/bd3f54ad-6867-4b8f-95ec-32d715d4da1d)


Richard

**Comment by JANGKOOK63** [comment]
Very thanks again.

SK.


2024년 2월 8일 (목) 오후 10:51, Báldogi Richárd ***@***.***>님이 작성:

**Comment by baldogiRichard** [comment]
Plug-in has been updated:

Fixed: When inserting a number based value into the IG the reports expect the format in string instead of number, so the .toString() have been called in line 160.
